### ISSUE TITLE
Concerns about Incorrect Results and a Suggestion for Paper Withdrawal

### ISSUE THREAD

**Issue by winterfell00** [MikeWangWZHL/EEG-To-Text#6]
I don't mean to offend, but the results reported in your paper are incorrect. If, under the correct testing procedure, the results are completely different from what is stated in your paper, I believe it would be best for you to withdraw it to prevent any potential spread of misinformation.

**Comment by A-Ayerh** [comment]
> I don't mean to offend, but the results reported in your paper are incorrect. If, under the correct testing procedure, the results are completely different from what is stated in your paper, I believe it would be best for you to withdraw it to prevent any potential spread of misinformation.

How were you able to run the eval_decoding.py file?
I'm running into errors:
AttributeError: 'list' object has no attribute 'squeeze'
AttributeError: 'list' object has no attribute 'tolist'

And if I comment those out then the BLEU scores all end up as 0.

**Comment by MikeWangWZHL** [comment]
@winterfell00 Thanks for the suggestion, we will update the paper to make the unintented bug in the testing procedure clear to prevent any further confusion; I have also made this clear in the README note
@A-Ayerh Thank you for the question, I have updated the .py eval_decoding.py file, let me know if the problem is still not fixed
